# Generated by Django 3.2.3 on 2021-06-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.ImageField(upload_to='')),
                ('news_title', models.TextField(max_length=255)),
                ('news_description', models.TextField(max_length=1000)),
                ('news_writer', models.CharField(blank=True, max_length=70, null=True)),
                ('news_visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('news_comments', models.IntegerField(blank=True, default=0, null=True)),
                ('news_tags', models.TextField(blank=True, default='', null=True)),
                ('news_category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('news_catid', models.IntegerField(default=0)),
                ('news_subcategory_name', models.CharField(blank=True, max_length=255, null=True)),
                ('news_subcatid', models.IntegerField(default=0)),
                ('news_added_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
