# Generated by Django 3.2.3 on 2021-06-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(default='', max_length=60)),
                ('visitor_email', models.CharField(default='', max_length=60)),
                ('visitor_text', models.TextField(default='')),
            ],
        ),
    ]
