# Generated by Django 3.2.3 on 2021-06-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_visitor_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.TextField(blank=True, default='', null=True)),
                ('address2', models.TextField(blank=True, default='', null=True)),
                ('email', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
